version: '3.8'

services:
  testTaskDB:
    image: postgres:latest
    restart: always
    container_name: testTaskDB
    environment:
      - POSTGRES_USER=${DB_USERNAME}

      - POSTGRES_PASSWORD=${DB_PASSWORD}

    volumes:
      - postgres:/var/lib/postgresql/data

    ports:
      - '${DB_PORT}:${DB_PORT}'

volumes:
  postgres:
